name: Build and deploy Node.js app to Azure Web App - newwebappdemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install, build, and test frontend
        run: |
          cd frontend  # Navigate to the frontend directory
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install, build, and test backend
        run: |
          cd newapp-backend  # Navigate to the backend directory
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip frontend and backend artifacts for deployment
        run: |
          cd frontend  # Navigate to the frontend directory
          zip -r ../release.zip .  # Zip frontend contents
          cd ../newapp-backend  # Navigate to the backend directory
          zip -r ../release.zip .  # Add backend contents to the same zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d deployment  # Unzip into a directory for deployment

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'newwebappdemo'  # Your Azure Web App name
          slot-name: 'Production'
          package: deployment  # Path to the unzipped contents
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_91E45C1F05C44A4DB86AD9D096546387 }}
